# 配置数据库连接驱动
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc://192.168.18.241:3306/ssm?serverTimezone=UTC
    username: root
    password: root
  # 配置redis端口和地址
  redis:
    host: 192.168.18.241
    port: 6379

# 配置mybatis的mapper关联文件
mybatis:
  type-aliases-package: com.mq.githubtest.domain
  mapper-locations: mapper/*.xml


