
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.241:3306/ssm?serverTimezone=UTC
    username: root
    password: root

  redis:
    host: 192.168.18.241
    port: 6379

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    # 控制台输出执行sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
